In [6]:
# 1.使用神经网络实现葡萄酒数据集的分类分析，分类值为葡萄酒质量，（1-10之间），选择不同的优化权重算法（solver）进行模型比较并分析。
#    *使用“quality”列
import warnings
warnings.filterwarnings('ignore')

#从数据集中读入数据
import pandas as pd
filename = "D:\mine_coding\CAU_IDS\data6\wine.csv"
data = pd.read_csv(filename, index_col='idx')
#数据预处理
data.drop('good_or_not',axis=1,inplace=True)
x = data.drop('quality', axis=1).values.astype(float)
y = data['quality'].values.astype(float)
#data.iloc[0:5,:]

In [7]:
#分割训练集和测试集
from sklearn import model_selection
X_train,X_test,y_train,y_test = model_selection.train_test_split(x,y,test_size=0.5,random_state=1)
print(X_train)

[[12.    0.46  2.96 ...  0.32  0.26  7.6 ]
 [10.8   0.4   3.32 ...  0.33  0.23  6.7 ]
 [ 8.9   0.42  2.89 ...  0.42  0.24  7.4 ]
 ...
 [10.9   0.43  3.25 ...  0.41  0.14  7.  ]
 [ 9.1   0.44  2.96 ...  0.42  0.28  7.4 ]
 [ 8.8   0.42  3.03 ...  0.53  0.25  6.4 ]]


In [8]:
#创建神经网络分类器，训练网络节点连接权重及偏置项（bfgs函数）
from sklearn.neural_network import MLPClassifier
mlp = MLPClassifier(solver='lbfgs',alpha=1e-5,hidden_layer_sizes=(5, 5),random_state=1)#表示有两个隐藏层，每层神经元个数分别为3、3
#random_state:作用:控制随机状态。对于结果是否重现，固定random_state是非常重要的。
#其实就是该组随机数的编号，在需要重复试验的时候，保证得到一组一样的随机数。
mlp.fit(X_train,y_train)
#mlp.score查看模型评分，返回给定测试数据和标签上的平均准确度
print(mlp.score(X_test,y_test))

0.4817855310415598


In [9]:
#分类器性能评估
from sklearn import metrics
y_predicted = mlp.predict(X_test)
print("Classification report for %s" % mlp)
print(metrics.classification_report(y_test, y_predicted) )
print( "Confusion matrix:\n", metrics.confusion_matrix(y_test, y_predicted) )

Classification report for MLPClassifier(alpha=1e-05, hidden_layer_sizes=(5, 5), random_state=1,
              solver='lbfgs')
              precision    recall  f1-score   support

         3.0       0.00      0.00      0.00         4
         4.0       0.00      0.00      0.00        70
         5.0       0.47      0.46      0.46       557
         6.0       0.49      0.77      0.59       894
         7.0       0.00      0.00      0.00       342
         8.0       0.00      0.00      0.00        80
         9.0       0.00      0.00      0.00         2

    accuracy                           0.48      1949
   macro avg       0.14      0.17      0.15      1949
weighted avg       0.36      0.48      0.41      1949

Confusion matrix:
 [[  0   0   3   1   0   0   0]
 [  0   0  26  44   0   0   0]
 [  0   0 254 303   0   0   0]
 [  0   0 209 685   0   0   0]
 [  0   0  38 304   0   0   0]
 [  0   0   7  73   0   0   0]
 [  0   0   0   2   0   0   0]]


In [10]:
#创建神经网络分类器，训练网络节点连接权重及偏置项（sgd函数）
mlp = MLPClassifier(solver='sgd',alpha=1e-5,hidden_layer_sizes=(3,3),random_state=1)#表示有两个隐藏层，每层神经元个数分别为3、3
mlp.fit(X_train,y_train)
print(mlp.score(X_test,y_test))

0.4586967675731144


In [11]:
#分类器性能评估
y_predicted = mlp.predict(X_test)
print("Classification report for %s" % mlp)
print(metrics.classification_report(y_test, y_predicted) )
print( "Confusion matrix:\n", metrics.confusion_matrix(y_test, y_predicted) )

Classification report for MLPClassifier(alpha=1e-05, hidden_layer_sizes=(3, 3), random_state=1,
              solver='sgd')
              precision    recall  f1-score   support

         3.0       0.00      0.00      0.00         4
         4.0       0.00      0.00      0.00        70
         5.0       0.00      0.00      0.00       557
         6.0       0.46      1.00      0.63       894
         7.0       0.00      0.00      0.00       342
         8.0       0.00      0.00      0.00        80
         9.0       0.00      0.00      0.00         2

    accuracy                           0.46      1949
   macro avg       0.07      0.14      0.09      1949
weighted avg       0.21      0.46      0.29      1949

Confusion matrix:
 [[  0   0   0   4   0   0   0]
 [  0   0   0  70   0   0   0]
 [  0   0   0 557   0   0   0]
 [  0   0   0 894   0   0   0]
 [  0   0   0 342   0   0   0]
 [  0   0   0  80   0   0   0]
 [  0   0   0   2   0   0   0]]


In [ ]:


#"D:\mine_coding\CAU_IDS\data6\wine.csv"

In [12]:
#2.基于Keras建立深度神经网络模型，采取不同的数据集划分比例（9:1，8:2，7:3），为葡萄酒数据集训练分类器并进行分析。
#    *使用“good_or_not”列

#（1）9:1
import pandas as pd
filename='data\wine.csv'
data=pd.read_csv(filename,index_col='idx')
data.loc[data['good_or_not']=='good','good_or_not']=1
data.loc[data['good_or_not']=='not','good_or_not']=0
data.drop('quality',axis=1,inplace=True)
x = data.drop('good_or_not', axis=1).values.astype(float)
y = data['good_or_not'].values.astype(float)
from keras.models import Sequential
from keras.layers import Dense, Activation
import numpy as np
from sklearn.model_selection import train_test_split
# 定义模型结构
model = Sequential()
model.add(Dense(units=16, input_dim=11))
model.add(Activation('relu'))
model.add(Dense(16))
model.add(Activation('relu'))
model.add(Dense(3))
model.add(Activation('softmax'))
#定义模型损失函数和优化器，并编译
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=["accuracy"])

#1、深度学习模型，输入输出都为多维张量，统一使用小写字母 x,y,划分比例9:1
x_train, x_test, y_train, y_test= train_test_split(x, y, train_size=0.9, test_size=0.1, random_state=0)#划分比例9:1
#x_train, x_test, y_train, y_test= train_test_split(x, y, train_size=0.8, test_size=0.2, random_state=0)#划分比例8:2
#x_train, x_test, y_train, y_test= train_test_split(x, y, train_size=0.7, test_size=0.3, random_state=0)#划分比例7:3
from keras.utils import np_utils
y_train_ohe = np_utils.to_categorical(y_train, num_classes = 3)
y_test_ohe = np_utils.to_categorical(y_test, num_classes = 3)

In [13]:
#2、模型的训练及评估
model.fit(x_train, y_train_ohe, epochs=20, batch_size=1, verbose=2, validation_data=(x_test,y_test_ohe))

Epoch 1/20
3508/3508 - 12s - loss: 1.3113 - accuracy: 0.6180 - val_loss: 0.6715 - val_accuracy: 0.6744 - 12s/epoch - 3ms/step
Epoch 2/20
3508/3508 - 12s - loss: 0.8441 - accuracy: 0.6417 - val_loss: 0.6029 - val_accuracy: 0.7026 - 12s/epoch - 3ms/step
Epoch 3/20
3508/3508 - 13s - loss: 0.7796 - accuracy: 0.6594 - val_loss: 0.6077 - val_accuracy: 0.6615 - 13s/epoch - 4ms/step
Epoch 4/20
3508/3508 - 10s - loss: 0.6888 - accuracy: 0.6759 - val_loss: 0.5953 - val_accuracy: 0.6897 - 10s/epoch - 3ms/step
Epoch 5/20
3508/3508 - 9s - loss: 0.6108 - accuracy: 0.6990 - val_loss: 0.5913 - val_accuracy: 0.6795 - 9s/epoch - 3ms/step
Epoch 6/20
3508/3508 - 10s - loss: 0.6116 - accuracy: 0.6787 - val_loss: 0.7150 - val_accuracy: 0.6590 - 10s/epoch - 3ms/step
Epoch 7/20
3508/3508 - 12s - loss: 0.6076 - accuracy: 0.6850 - val_loss: 0.5645 - val_accuracy: 0.6974 - 12s/epoch - 4ms/step
Epoch 8/20
3508/3508 - 12s - loss: 0.5866 - accuracy: 0.6870 - val_loss: 0.5775 - val_accuracy: 0.6949 - 12s/epoch - 3ms

In [14]:
#3、评估模型
loss, accuracy = model.evaluate(x_test, y_test_ohe,verbose=2)
print('loss = {},accuracy = {} '.format(loss,accuracy) )

13/13 - 0s - loss: 0.5285 - accuracy: 0.7231 - 350ms/epoch - 27ms/step
loss = 0.5285254120826721,accuracy = 0.7230769395828247 


In [ ]:
#4、查看预测结果
prob = model.predict(x_test,verbose=2)
#classes = model.predict_classes(x_test,verbose=2)
classes=np.argmax(prob,axis=1)
print('测试样本数：',len(classes))
print("分类概率:\n",prob)
print("分类结果：\n",classes)
from sklearn.metrics import classification_report
print('分类性能报告如下：')
print(classification_report(list(y_test),list(classes)))

In [15]:
#（2）8:2
import pandas as pd
filename='data\wine.csv'
data=pd.read_csv(filename,index_col='idx')
data.loc[data['good_or_not']=='good','good_or_not']=1
data.loc[data['good_or_not']=='not','good_or_not']=0
data.drop('quality',axis=1,inplace=True)
x = data.drop('good_or_not', axis=1).values.astype(float)
y = data['good_or_not'].values.astype(float)
from keras.models import Sequential
from keras.layers import Dense, Activation
import numpy as np
from sklearn.model_selection import train_test_split
# 定义模型结构
model = Sequential()
model.add(Dense(units=16, input_dim=11))
model.add(Activation('relu'))
model.add(Dense(16))
model.add(Activation('relu'))
model.add(Dense(3))
model.add(Activation('softmax'))
#定义模型损失函数和优化器，并编译
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=["accuracy"])

#1、深度学习模型，输入输出都为多维张量，统一使用小写字母 x,y,划分比例8:2
#x_train, x_test, y_train, y_test= train_test_split(x, y, train_size=0.9, test_size=0.1, random_state=0)#划分比例9:1
x_train, x_test, y_train, y_test= train_test_split(x, y, train_size=0.8, test_size=0.2, random_state=0)#划分比例8:2
#x_train, x_test, y_train, y_test= train_test_split(x, y, train_size=0.7, test_size=0.3, random_state=0)#划分比例7:3
from keras.utils import np_utils
y_train_ohe = np_utils.to_categorical(y_train, num_classes = 3)
y_test_ohe = np_utils.to_categorical(y_test, num_classes = 3)

In [16]:
#2、模型的训练及评估
model.fit(x_train, y_train_ohe, epochs=20, batch_size=1, verbose=2, validation_data=(x_test,y_test_ohe))

Epoch 1/20
3118/3118 - 11s - loss: 0.7412 - accuracy: 0.6495 - val_loss: 0.6723 - val_accuracy: 0.6833 - 11s/epoch - 3ms/step
Epoch 2/20
3118/3118 - 13s - loss: 0.6263 - accuracy: 0.6684 - val_loss: 0.6537 - val_accuracy: 0.6269 - 13s/epoch - 4ms/step
Epoch 3/20
3118/3118 - 12s - loss: 0.6121 - accuracy: 0.6703 - val_loss: 0.5686 - val_accuracy: 0.6885 - 12s/epoch - 4ms/step
Epoch 4/20
3118/3118 - 13s - loss: 0.5948 - accuracy: 0.6764 - val_loss: 0.5686 - val_accuracy: 0.6949 - 13s/epoch - 4ms/step
Epoch 5/20
3118/3118 - 12s - loss: 0.5902 - accuracy: 0.6796 - val_loss: 0.5677 - val_accuracy: 0.6808 - 12s/epoch - 4ms/step
Epoch 6/20
3118/3118 - 13s - loss: 0.5787 - accuracy: 0.6953 - val_loss: 0.5648 - val_accuracy: 0.7128 - 13s/epoch - 4ms/step
Epoch 7/20
3118/3118 - 14s - loss: 0.5707 - accuracy: 0.6944 - val_loss: 0.5697 - val_accuracy: 0.7000 - 14s/epoch - 5ms/step
Epoch 8/20
3118/3118 - 9s - loss: 0.5624 - accuracy: 0.7021 - val_loss: 0.5603 - val_accuracy: 0.6872 - 9s/epoch - 3ms

In [17]:
#3、评估模型
loss, accuracy = model.evaluate(x_test, y_test_ohe,verbose=2)
print('loss = {},accuracy = {} '.format(loss,accuracy) )

25/25 - 0s - loss: 0.5496 - accuracy: 0.7077 - 368ms/epoch - 15ms/step
loss = 0.5495900511741638,accuracy = 0.7076923251152039 


In [18]:
#4、查看预测结果
prob = model.predict(x_test,verbose=2)
#classes = model.predict_classes(x_test,verbose=2)
classes=np.argmax(prob,axis=1)
print('测试样本数：',len(classes))
print("分类概率:\n",prob)
print("分类结果：\n",classes)
from sklearn.metrics import classification_report
print('分类性能报告如下：')
print(classification_report(list(y_test),list(classes)))

25/25 - 0s - 284ms/epoch - 11ms/step
测试样本数： 780
分类概率:
 [[5.0521880e-01 4.9478111e-01 2.5011893e-10]
 [4.9381831e-01 5.0618172e-01 4.8269191e-11]
 [8.9934416e-02 9.1006559e-01 2.6546437e-30]
 ...
 [4.1548929e-01 5.8451074e-01 5.2177198e-16]
 [2.0414397e-01 7.9585600e-01 8.0851929e-29]
 [3.1550586e-01 6.8449414e-01 8.0429778e-23]]
分类结果：
 [0 1 1 0 1 1 1 1 1 1 0 1 0 0 0 1 1 1 1 1 1 1 1 0 1 0 1 1 0 0 1 0 1 0 1 1 0
 1 0 0 0 0 1 0 1 0 1 1 1 1 1 1 1 1 0 1 1 1 0 1 1 1 1 0 1 1 1 0 1 0 1 1 1 0
 1 1 0 1 1 1 1 0 1 1 1 1 1 1 0 0 1 1 1 1 1 1 0 1 0 1 0 1 1 1 1 1 1 1 1 0 0
 1 0 0 1 0 0 1 1 0 1 1 1 1 0 1 0 1 0 1 1 1 1 0 1 1 1 1 0 1 1 0 1 0 1 1 1 1
 1 0 1 0 0 1 0 0 0 0 1 1 1 0 1 1 1 1 1 0 0 1 0 1 0 1 1 1 1 1 1 1 1 0 0 1 1
 0 1 1 0 1 1 1 0 0 1 1 1 1 1 1 1 1 1 0 1 1 0 1 0 1 1 0 1 1 1 1 1 1 1 1 0 0
 0 1 1 0 1 1 0 1 1 1 0 0 1 1 0 0 0 1 1 0 1 1 0 0 1 1 1 1 1 0 1 1 0 0 1 1 0
 1 1 0 0 1 1 1 0 0 1 1 1 1 1 0 0 0 1 1 0 1 0 0 1 0 1 1 0 1 0 1 1 1 1 1 1 0
 1 0 1 1 0 1 1 0 1 0 1 1 1 0 1 1 1 1 1 0 1 0 1 1 1 0 0 1 1 1 0

In [19]:
#（3）7:3
import pandas as pd
filename='data\wine.csv'
data=pd.read_csv(filename,index_col='idx')
data.loc[data['good_or_not']=='good','good_or_not']=1
data.loc[data['good_or_not']=='not','good_or_not']=0
data.drop('quality',axis=1,inplace=True)
x = data.drop('good_or_not', axis=1).values.astype(float)
y = data['good_or_not'].values.astype(float)
from keras.models import Sequential
from keras.layers import Dense, Activation
import numpy as np
from sklearn.model_selection import train_test_split
# 定义模型结构
model = Sequential()
model.add(Dense(units=16, input_dim=11))
model.add(Activation('relu'))
model.add(Dense(16))
model.add(Activation('relu'))
model.add(Dense(3))
model.add(Activation('softmax'))
#定义模型损失函数和优化器，并编译
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=["accuracy"])

#1、深度学习模型，输入输出都为多维张量，统一使用小写字母 x,y,划分比例7:3
#x_train, x_test, y_train, y_test= train_test_split(x, y, train_size=0.9, test_size=0.1, random_state=0)#划分比例9:1
#x_train, x_test, y_train, y_test= train_test_split(x, y, train_size=0.8, test_size=0.2, random_state=0)#划分比例8:2
x_train, x_test, y_train, y_test= train_test_split(x, y, train_size=0.7, test_size=0.3, random_state=0)#划分比例7:3
from keras.utils import np_utils
y_train_ohe = np_utils.to_categorical(y_train, num_classes = 3)
y_test_ohe = np_utils.to_categorical(y_test, num_classes = 3)

In [20]:
#2、模型的训练及评估
model.fit(x_train, y_train_ohe, epochs=20, batch_size=1, verbose=2, validation_data=(x_test,y_test_ohe))

Epoch 1/20
2728/2728 - 12s - loss: 0.9290 - accuracy: 0.6045 - val_loss: 0.8949 - val_accuracy: 0.6803 - 12s/epoch - 5ms/step
Epoch 2/20
2728/2728 - 10s - loss: 0.6398 - accuracy: 0.6697 - val_loss: 0.5574 - val_accuracy: 0.6991 - 10s/epoch - 4ms/step
Epoch 3/20
2728/2728 - 11s - loss: 0.6200 - accuracy: 0.6694 - val_loss: 0.5959 - val_accuracy: 0.6966 - 11s/epoch - 4ms/step
Epoch 4/20
2728/2728 - 12s - loss: 0.6125 - accuracy: 0.6591 - val_loss: 0.5790 - val_accuracy: 0.6795 - 12s/epoch - 4ms/step
Epoch 5/20
2728/2728 - 10s - loss: 0.5958 - accuracy: 0.6855 - val_loss: 0.6664 - val_accuracy: 0.6872 - 10s/epoch - 4ms/step
Epoch 6/20
2728/2728 - 12s - loss: 0.5841 - accuracy: 0.6789 - val_loss: 0.5714 - val_accuracy: 0.6880 - 12s/epoch - 4ms/step
Epoch 7/20
2728/2728 - 11s - loss: 0.5790 - accuracy: 0.6741 - val_loss: 0.5528 - val_accuracy: 0.7000 - 11s/epoch - 4ms/step
Epoch 8/20
2728/2728 - 10s - loss: 0.5704 - accuracy: 0.6848 - val_loss: 0.5522 - val_accuracy: 0.6983 - 10s/epoch - 4

In [21]:
#3、评估模型
loss, accuracy = model.evaluate(x_test, y_test_ohe,verbose=2)
print('loss = {},accuracy = {} '.format(loss,accuracy) )

37/37 - 0s - loss: 0.5491 - accuracy: 0.7017 - 444ms/epoch - 12ms/step
loss = 0.5490941405296326,accuracy = 0.7017093896865845 


In [22]:
#4、查看预测结果
prob = model.predict(x_test,verbose=2)
#classes = model.predict_classes(x_test,verbose=2)
classes=np.argmax(prob,axis=1)
print('测试样本数：',len(classes))
print("分类概率:\n",prob)
print("分类结果：\n",classes)
from sklearn.metrics import classification_report
print('分类性能报告如下：')
print(classification_report(list(y_test),list(classes)))

37/37 - 0s - 171ms/epoch - 5ms/step
测试样本数： 1170
分类概率:
 [[5.1072192e-01 4.8927808e-01 7.0522209e-19]
 [5.9279329e-01 4.0720668e-01 5.7798575e-26]
 [1.6268173e-01 8.3731830e-01 3.7906242e-31]
 ...
 [3.9935565e-01 6.0064435e-01 2.2825230e-22]
 [5.2808827e-01 4.7191176e-01 9.1365866e-11]
 [1.4159493e-01 8.5840505e-01 8.0374224e-19]]
分类结果：
 [0 0 1 ... 1 0 1]
分类性能报告如下：
              precision    recall  f1-score   support

         0.0       0.54      0.48      0.51       374
         1.0       0.77      0.81      0.79       796

    accuracy                           0.70      1170
   macro avg       0.65      0.64      0.65      1170
weighted avg       0.69      0.70      0.70      1170

